import { RouteInfo } from "./sidebar.metadata";
export const ROUTES: RouteInfo[] = [
  {
    path: "/admin/dashboard/searchmember",
    title: "Search Member",
    moduleName: "dashboard",
    iconType: "material-icons-two-tone",
    icon: "event_note",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["0", "Doctor"],
    submenu: [],
  },
  {
    path: "/admin/dashboard/registermember",
    title: "Register Member",
    moduleName: "dashboard",
    iconType: "material-icons-two-tone",
    icon: "event_note",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["0", "Doctor"],
    submenu: [],
  },
  {
    path: "/admin/dashboard/addbenefitplan",
    title: "Benefit Plan",
    moduleName: "dashboard",
    iconType: "material-icons-two-tone",
    icon: "event_note",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["0", "Doctor"],
    submenu: [],
  },
  {
    path: "/admin/dashboard/assigned-benefit-plan",
    title: "Assign Benefit Plan",
    moduleName: "dashboard",
    iconType: "material-icons-two-tone",
    icon: "event_note",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["0", "Doctor"],
    submenu: [],
  },
  {
    path: "/admin/dashboard/membersummary",
    title: "Member Summary",
    moduleName: "dashboard",
    iconType: "material-icons-two-tone",
    icon: "event_note",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["0", "Doctor"],
    submenu: [],
  },
  // Admin Modules
  // {
  //   path: "",
  //   title: "MENUITEMS.DASHBOARD.TEXT",
  //   moduleName: "dashboard",
  //   iconType: "material-icons-two-tone",
  //   icon: "space_dashboard",
  //   class: "menu-toggle",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   role: ["Admin"],
  //   submenu: [
  //     {
  //       path: "/admin/dashboard/main",
  //       title: "MENUITEMS.DASHBOARD.LIST.DASHBOARD1",
  //       moduleName: "dashboard",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       submenu: [],
  //     },
  //     {
  //       path: "/admin/dashboard/dashboard2",
  //       title: "MENUITEMS.DASHBOARD.LIST.DASHBOARD2",
  //       moduleName: "dashboard",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       submenu: [],
  //     },
  //   ],
  // },
];
